Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using netbooks.Models;

namespace netbooks.Controllers
{
    public class BookController : Controller
    {
        private DataContext context { get; set; }
        public BookController(DataContext ctx)
        {
            context = ctx;
        }

        [HttpGet]
        [Route("Book/Add")]

        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            return View("Edit", new Book());
        }
        [HttpGet]
        [Route("Book/Edit/{id}")]
        public IActionResult Edit(long id)
        {
            ViewBag.Action = "Edit";
            var book = context.Books.Find(id);
            return View(book);
        }
        [HttpPost]
        public IActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                if (book.BookId == 0)
                    context.Books.Add(book);
                else
                    context.Books.Update(book);
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Action = (book.BookId == 0) ? "Add" : "Edit";
                return View(book);
            }
        }
        [HttpGet]
        [Route("Book/Delete/{id}")]
        public IActionResult Delete(long id)
        {
            var book = context.Books.Find(id);
            return View(book);
        }
        [HttpPost]
        public IActionResult Delete(Book book)
        {
            context.Books.Remove(book);
            context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

    }
}

Controllers/ReviewController.cs
using Microsoft.AspNetCore.Mvc;
using netbooks.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace netbooks.Controllers
{
    
    public class ReviewController : Controller
    {
        private DataContext context { get; set; }
        public ReviewController(DataContext ctx)
        {
            context = ctx;
        }

        [HttpGet]
        [Route("Review/List/{id}")]
        public IActionResult List(long id)
        {
            //return Content("Review controller, List action id=" + id);
            ViewBag.Action = "List";

            var book = context.Books.Find(id);
            var reviews = context.Reviews.Where(r => r.BookId == id);
            book.Reviews = reviews.ToList();
            //Console.WriteLine("book review count=" + book.Reviews.Count);
            if (book.Reviews == null)
                book.Reviews = new List<Review>();
            return View(book);
        }
        [HttpGet]
        [Route("Review/Add/{id}")]
        public IActionResult Add(long id)
        {
            ViewBag.Action = "Add";
            var book = context.Books.Find(id);
            book.Reviews = new List<Review>();
            var nreview = new Review();
            nreview.BookId = book.BookId;
            book.Reviews.Add(nreview);
            return View("Edit", book);
        }
        [HttpGet]
        [Route("Review/Edit/{id}")]
        public IActionResult Edit(long id)
        {
            ViewBag.Action = "Edit";
            var review = context.Reviews.Find(id);
            var book = context.Books.Find(review.BookId);
            book.Reviews = new List<Review>();
            book.Reviews.Add(review);
            return View("Edit", book);
        }
        [HttpPost]
        [Route("Review/Edit/{id?}")]
        public IActionResult Edit(Review review, long id)
        {
            //Console.WriteLine("BookId = " + review.BookId);
            if (ModelState.IsValid && review.BookId > 0)
            {
                if (review.ReviewId == 0)
                    context.Reviews.Add(review);
                else
                    context.Reviews.Update(review);
                context.SaveChanges();
                return Redirect("/netbooks/List/" + review.BookId);
            }
            else
            {
                ViewBag.Action = (review.ReviewId == 0) ? "Add" : "Edit";
                return View(review);
            }
        }
        [HttpGet]
        public IActionResult Delete(long id)
        {
            ViewBag.Action = "Delete";
            var review = context.Reviews.Find(id);
            var book = context.Books.Find(review.BookId);
            book.Reviews = new List<Review>();
            book.Reviews.Add(review);
            return View("Delete", book);
        }
        [HttpPost]
        public IActionResult Delete(Review review)
        {
            review = context.Reviews.Find(review.ReviewId);
            var bookId = review.BookId;
            context.Reviews.Remove(review);
            context.SaveChanges();
            return Redirect("/netbooks/List/" + bookId);
        }

    }
}

Views/Review/Delete.cshtml
@model Book
@{
    ViewBag.Title = ViewBag.Action + " Review";
    var review = Model.Reviews[0];
}
<h2>@ViewBag.Title</h2>
<table class="table table-bordered table-striped">
    <tr>
        <td>Title</td>
        <td>@Model.Title</td>
    </tr>
    <tr>
        <td>Author</td>
        <td>@Model.Author</td>
    </tr>
    <tr>
        <td>Rating</td>
        <td>@Model.Rating</td>
    </tr>
</table>
<br />
<h2>Confirm Deletion</h2>
<h3>Review @review.ReviewId by @review.Author</h3>
<form asp-action="Delete" asp-route-id="BookId" method="post">
    <input type="hidden" asp-for="@review.ReviewId" />
    <button type="submit" class="btn btn-primary">Delete</button>
    <a asp-controller="Review" asp-action="List" asp-route-id="@Model.BookId" class="btn btn-primary">Cancel</a>
</form>

Views/Review/Edit.cshtml
@model Book
@{
    ViewBag.Title = ViewBag.Action + " Review";
    var review = Model.Reviews[0];
}
<h2>@ViewBag.Title</h2>
<table class="table table-bordered table-striped">
    <tr>
        <td>Id</td>
        <td>@Model.BookId</td>
    </tr>
    <tr>
        <td>Title</td>
        <td>@Model.Title</td>
    </tr>
    <tr>
        <td>Author</td>
        <td>@Model.Author</td>
    </tr>
    <tr>
        <td>Rating</td>
        <td>@Model.Rating</td>
    </tr>
</table>
<br />


<form asp-action="Edit" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="@review.Author">Review Author</label>
        <input asp-for="@review.Author" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="@review.Comment">Review</label>
        <textarea asp-for="@review.Comment" class="form-control" text-wrap:normal" type="text"
            placeholder="Please add your review here"></textarea>
    </div>
    <div class="form-group">
        <label asp-for="@review.Rating">Rating</label>
        <input asp-for="@review.Rating" class="form-control">
    </div>

    <input type="hidden" asp-for="@review.BookId" />
    @if (@review.ReviewId > 0)
    {
        <input type="hidden" asp-for="@review.ReviewId" />
    }
    <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
    <!--a asp-controller="Book" asp-action="Index" asp-route-id="BookId" class="btn btn-primary">Cancel</a-->
    <a asp-controller="Review" asp-action="List" asp-route-id="@Model.BookId" class="btn btn-primary">Cancel</a>
</form>

Views/Review/List.cshtml
@model Book
@{
    ViewBag.Title = "Books";
}
<h2>List</h2>

<table class="table table-bordered table-striped">
    <tr>
        <td>Title</td>
        <td>@Model.Title</td>
    </tr>
    <tr>
        <td>Author</td>
        <td>@Model.Author</td>
    </tr>
    <tr>
        <td>Rating</td>
        <td>@Model.Rating</td>
    </tr>
</table>
<br />
<a asp-controller="Review" asp-action="Add" asp-route-id="@Model.BookId">Add Review</a>
@if (Model.Reviews.Count() > 0)
{
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Author</th>
                <th>Review</th>
                <th>Rating</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var review in Model.Reviews)
            {
                <tr>
                    <td>@review.ReviewId</td>
                    <td>@review.Author</td>
                    <td>@review.Comment</td>
                    <td>@review.Rating</td>
                    <td>
                        <a asp-controller="Review" asp-action="Edit" asp-route-id="@review.ReviewId">Edit</a>
                        <a asp-controller="Review" asp-action="Delete" asp-route-id="@review.ReviewId">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}